---
title: "dm_abundance"
date: "20 January 2026"
output: html_document
author: "Elizabeth Daigle"
---
# Read in packages, functions, and directories
```{r}
source(paste0(here::here(), "/1-Config/config.R"))
```

# Read in sample metadata
```{r}
meta <- read_tsv(paste0(configDir, "/sampleReadList.txt"))
```

# Read in dsrAB gene counts
```{r}
# capsule data
capsule <- read_tsv(paste0(abundanceDir, "/Capsule/concat_dsrAB_Capsule_Abundances_RPKG.txt"))
# stool data
stool <- read_tsv(paste0(abundanceDir, "/Stool/concat_dsrAB_Stool_Abundances_RPKG.txt"))
# combine capsule and stool data
samples <- bind_rows(capsule, stool) %>%
  mutate(subject=as.numeric(str_extract(.$coassembly, "\\d+")))
```

```{r}
#which hits are dups?
# want to make sure they all get filtered out since they have NA for distance
closest_ref_2015 <- read_csv(paste0(dataDir, "closestRefInfo_allScoreThresholdHits_wSingleClosestRef_capsule_2015.csv")) 
dups <- closest_ref_2015 %>%
  filter(is.na(distance))

samples_no_dups <- samples %>%
  filter(!geneLoc %in% dups$hit_id)
```

```{r}
# filter and remove duplicate genes
samples_unique_genes <- samples_no_dups %>%
# Remove RPKGs of 0 (feature counts keeps genes even when nothing has mapped to them) 
  filter(RPKG>0) %>%
# make subject a factor
  mutate(subject = factor(subject)) %>%
# add capsule type (1,2,3,4, most proximal to most distal)
  left_join(meta %>% select(samplename, Type, Set), 
            by = c("sample" = "samplename")) %>%
# filter for unique genes in each sample
# want to keep gene domain with the highest score, if there is a tie return just the first hit encountered
  group_by(geneID, sample) %>%
  slice_max(Score, n = 1, with_ties = FALSE) %>%
  ungroup()
```
# Read in closest reference leaf info; only 2015 references
```{r}
closest_ref <-  read_csv(paste0(dataDir, "closestRefInfo_allScoreThresholdHits_wSingleClosestRef_capsule.csv"))
closest_ref_2015 <- read_csv(paste0(dataDir, "closestRefInfo_allScoreThresholdHits_wSingleClosestRef_capsule_2015.csv"))
```

# Add a column to samples that has the single_closest_ref
```{r}
samples_unique_genes_with_names <- samples_unique_genes %>% filter(geneLoc %in% closest_ref$hit_id) %>%
  left_join(closest_ref %>% select(hit_id, single_closest_ref, distance),
            by = c("geneLoc" = "hit_id")) %>% 
  mutate(sample_type = ifelse(grepl("Stool", coassembly), "Stool", "Capsule"))

saveRDS(samples_unique_genes_with_names, file = paste0(dataDir, "/samples_unique_genes_with_names.rds"))


samples_unique_genes_with_names_2015 <- samples_unique_genes %>% filter(geneLoc %in% closest_ref_2015$hit_id) %>%
  left_join(closest_ref_2015 %>% select(hit_id, single_closest_ref, distance),
            by = c("geneLoc" = "hit_id")) %>% 
  mutate(sample_type = ifelse(grepl("Stool", coassembly), "Stool", "Capsule"))

saveRDS(samples_unique_genes_with_names_2015, file = paste0(dataDir, "/samples_unique_genes_with_names_2015.rds"))
```

## for the asr genes 
```{r}
asr <- read_tsv(paste0(dataDir, "/concat_asrABC_Abundances_RPKM_redo.txt")) %>%
  mutate(subject=as.numeric(str_extract(.$coassembly, "\\d+")))  %>% 
  mutate(sample_type = ifelse(grepl("Stool", coassembly), "Stool", "Capsule"))

# filter and remove duplicate genes
asr_unique_cluster <- asr %>%
  mutate(RPKG = as.numeric(RPKG)) %>%
# Remove RPKGs of 0 (feature counts keeps genes even when nothing has mapped to them) 
  filter(RPKG>0) %>%
  mutate(subject = factor(subject)) %>%
# add capsule type
  left_join(meta %>% select(samplename, Type), 
            by = c("sample" = "samplename")) %>%
# add name for closest ref for asr (most BLAST results gave Firmicutes)
  mutate(single_closest_ref="likely Firmicutes") %>%
# filter for unique genes in each sample
# want to keep gene domain with the highest score, if there is a tie return just the first hit encountered
  group_by(geneID, sample) %>%
  slice_max(Score, n = 1, with_ties = FALSE) %>%
  ungroup() 

# filtering by geneID leaves different genes with the same geneNum/locations, and you end up with more than 3 hits for each contig

saveRDS(asr_unique_cluster, file = paste0(dataDir, "/asr_unique_cluster.rds"))


```



