---
title: "NCBI tree figures"
output: html_document
author: "Elizabeth Daigle"
date: "7 May 2026"
---
# Read in packages, functions, and directories
```{r}
source(paste0(here::here(), "/1-Config/config.R"))
```

```{r}
#root tree
ref_tree <- read.tree(paste0(raxmlDir, "/RAxML_originalLabelledTree_noBootstrap_no_2018_assemblies.newick"))
rooted_ref_tree <- root(ref_tree, c("Moorella_thermoacetica_Y72_copy_2__MooTher5"), r = TRUE)
```

# read in the taxa table
```{r}
taxa_table <- read_csv(paste0(taxaDir, "/taxa_table_0420.csv"))
```

# remove oxidative bacterial node and moorella thermoacetica cp 2
```{r}
# also referenced in hit_clusters_tree.Rmd
moorella_copy_2_labels <- c("Moorella_thermoacetica_Y72_copy_2__MooTher5", "Moorella_thermoacetica_ATCC_39073_copy_2__MooThe10")
ox_bact_labels <- subset(taxa_table$OTU, taxa_table$dsrab_type == "Oxidative bacterial type DsrAB")

#prune tree (this is also referenced in ani_zoom_trees.Rmd)
pruned_tree <- tidytree::drop.tip(rooted_ref_tree, c(moorella_copy_2_labels, ox_bact_labels))

```

# get otu table for labeling tree
```{r}
closestRefInfo_allScoreThresholdHits_singleRefOnly <- read_csv(paste0(dataDir, "closestRefInfo_allScoreThresholdHits_wSingleClosestRef_no_2018.csv"))
hits_final <- readRDS(paste0(dataDir, "/hits_final_sample_prev.rds"))

hit_otus <- unique(subset(hits_final$single_closest_ref, hits_final$distance < 2.5 & hits_final$SRM_present == TRUE))
hit_otus <- gsub("[.]", "-", hit_otus)
hit_otus <- gsub("sp-", "sp.", hit_otus)
hit_otus <- gsub("sk-", "sk.", hit_otus)
hit_otus <- gsub("str-", "str.", hit_otus)
```


# nodes
```{r}
faca_node = intersect(as.vector(subset(taxa_table$OTU, taxa_table$supercluster == "FACA group sensu lato")), pruned_tree$tip.label)

desulfovibrionaceae_node = intersect(as.vector(subset(taxa_table$OTU, taxa_table$level3_taxon == "Desulfovibrionaceae")), pruned_tree$tip.label)

archaeoglobus_node = intersect(as.vector(subset(taxa_table$OTU, taxa_table$supercluster == "Archaeoglobus cluster")), pruned_tree$tip.label)

env_supercluster1_node = intersect(as.vector(subset(taxa_table$OTU, taxa_table$supercluster == "Environmental supercluster 1")), pruned_tree$tip.label)

deltaproteobacteria_node = intersect(as.vector(subset(taxa_table$OTU, taxa_table$level2_taxon == "Deltaproteobacteria")), pruned_tree$tip.label)

moorella_node = MRCA(rooted_ref_tree, c('Moorella_thermoacetica_Y72_copy_2__MooTher5', "Moorella_thermoacetica_ATCC_39073_copy_2__MooThe10"))

red_arch_node = c("Caldivirga_maquilingensis__CvgMaqu3", "Pyrobaculum_oguniense_copy_1__PyrOgun6") 

oxbact_node = MRCA(rooted_ref_tree, c("Thiocapsa_rosea_DSM_235__ThpRos10", "Magnetococcus_marinus__Z04Spec2"))

nitrospirae_node <- intersect(as.vector(subset(taxa_table$OTU, taxa_table$supercluster == "Nitrospirae supercluster")), pruned_tree$tip.label)

```


# circular tree
```{r}

tree <- ggtree(pruned_tree, layout = "circular", linewidth = 0.15) +
  theme(plot.title = element_text(hjust = 0.5, size = 13), legend.title = element_text(hjust = 0.5, size = 8))


```

# iterated clade hilights by taxonomic level
```{r}
# library(RColorBrewer)
tree <- ggtree(pruned_tree, layout = "circular", size = 0.15) +
  theme(plot.title = element_text(hjust = 0.5, size = 13), legend.title = element_text(hjust = 0.5, size = 8))

taxa <- as.vector(unique(taxa_table$supercluster))

deltaproteobacteria_node <- c("Desulfobacca_acetoxidans__DebAcet3", "Desulfovibrio_magneticus__AP010904")

# hit_otus <- otu_hits_table$Var
# hit_otus <- unique(subset(closestRefInfo_allScoreThresholdHits_singleRefOnly$closest_single_ref, closestRefInfo_allScoreThresholdHits_singleRefOnly$distance < 2.5 & !is.na(closestRefInfo_allScoreThresholdHits_singleRefOnly$closest_single_ref)))
# hit_otus <- gsub("[.]", "-", hit_otus)
# hit_otus <- gsub("sp-", "sp.", hit_otus)
# hit_otus <- gsub("sk-", "sk.", hit_otus)
# hit_otus <- gsub("str-", "str.", hit_otus)

colors <- brewer.pal(7, "Set2")
purple <- brewer.pal(10, "Set3")[10]
n = 1

for (taxon in taxa) {
  if (!is.na(taxon) & taxon != "Deltaproteobacteria supercluster") {

    node <- intersect(as.vector(subset(taxa_table$OTU, taxa_table$supercluster == taxon)), pruned_tree$tip.label)

  if ((length(node) > 0)) {

    tree <-
      tree +
      # geom_hilight(node = MRCA(pruned_tree, node), color = colors[n], alpha = 0) +
      # geom_cladelab(node = MRCA(pruned_tree, node), label = taxon, fontsize = 3.5, horizontal = F, hjust = 0.5, vjust = 1.5, barcolor = colors[n], align = T, barsize = 1)
      geom_cladelab(node = MRCA(pruned_tree, node), label = "", fontsize = 3.5, horizontal = F, hjust = 0.5, vjust = 1.5, barcolor = colors[n], align = T, barsize = 1)

    n = n +1
    }
  }
}

tree <-
  tree +
      # geom_hilight(node = MRCA(pruned_tree, deltaproteobacteria_node), color = colors[n], alpha = 0) +
      # geom_cladelab(node = MRCA(pruned_tree, deltaproteobacteria_node), label = "Deltaproteobacteria supercluster", fontsize = 3.5, horizontal = F, hjust = 0.5, vjust = 1.5, barcolor = colors[n], align = T, barsize = 1) +
  geom_cladelab(node = MRCA(pruned_tree, deltaproteobacteria_node), label = "", fontsize = 3.5, horizontal = F, hjust = 0.5, vjust = 1.5, barcolor = colors[n], align = T, barsize = 1) +

  # geom_hilight(node = MRCA(pruned_tree, red_arch_node), color = colors[n+1], alpha = 0) +
      # geom_cladelab(node = MRCA(pruned_tree, red_arch_node), label = "reductive archaeal type DsrAB", fontsize = 3.5, horizontal = F, hjust = 0.5, vjust = 1.5, barcolor = colors[n+1], align = T, barsize = 1) +
  geom_cladelab(node = MRCA(pruned_tree, red_arch_node), label = "", fontsize = 3.5, horizontal = F, hjust = 0.5, vjust = 1.5, barcolor = colors[n+1], align = T, barsize = 1) +

  geom_hilight(node = MRCA(pruned_tree, faca_node), fill = colors[2], alpha = 0.2) +
  geom_hilight(node = MRCA(pruned_tree, desulfovibrionaceae_node), fill = purple, alpha = 0.2) +

  geom_tippoint(aes(subset= label %in% hit_otus), size = 0.5, color = "red", alpha = 0.8, position = "jitter")

tree
ggsave(plot = tree,file = paste0(figureDir, "circular_tree.jpeg"), width = 5, height = 5)
```
```{r}
species_labels <- c("Desulfitibacter_alkalitolerans__DfiAlka2" = "italic(Desulfitibacter~alkalitolerans)",
                    "Desulfovibrio_piger__DslPige3" = "italic(Desulfovibrio~piger~3)",
                    "Desulfovibrio_piger__DslPige4" = "italic(Desulfovibrio~piger~4)",
                    "Bilophila_wadsworthia__BilWads6" = "italic(Bilophila~wadsworthia~6)",
                    "uncultured_bacterium__EF645667" = "uncultured~italic(Desulfovibrio)~species~EF645667",
                    "Bilophila_sp._4_1_30__BilSpec3" = "italic(Bilophila~species~3)",
                    "Gordonibacter_pamelaeae__GrdPame5" = "italic(Gordonibacter~pamelaeae)",
                    "Gordonibacter_pamelaeae_7-10-1-b__FP929047" = "italic(Gordonibacter~pamelaeae)~FP929047",
                    "Anaerobic_bacterium_sk.prop8__Bv2Prop2" = "'uncultured Firmicute from industrial environment AY751286'",
                    "Desulfovibrio_piger__DslPige2" = "italic(Desulfovibrio~piger~2)",
                    "Candidatus_Desulfovibrio_trichonymphae" = "italic(Candidatus~Desulfovibrio~trichonymphae)",
                    "Desulfovibrio_desulfuricans_subsp._desulfuricans_str._ATCC_27774__CP001358" = "italic(Desulfovibrio~desulfuricans)~subsp.~desulfuricans",
                    "Desulfovibrio_vulgaris__DQ826729" = "italic(Desulfovibrio~vulgaris)",
                    "MSW_digester_clone__Unc01cxc" = "'uncultured Firmicute from digester'",
                    "Desulfovibrio_desulfuricans__DslDes17" = "italic(Desulfovibrio~desulfuricans)~AJ249777",
                    "Desulfovibrio_sp._6_1_46AFAA__DsvSp231" = "italic(Desulfovibrio)~species~ACWM01000066",
                    "Desulfovibrio_sp._3_1_syn3__DsvSp230" = "italic(Desulfovibrio)~species~ADDR01000049",
                    "Thermodesulfobium_narugense__CP002690" = "italic(Thermodesulfobium~narugense)",
                    "Desulfosporosinus_youngiae__DfpYoun5" = "italic(Desulfosporosinus~youngiae)",
                    "Arctic_sediment_clone_AH5_5__AtcSed67" = "'uncultured Firmicute from arctic sediment'", 
                    "Archaeoglobus_sulfaticallidus__ArgSulfa" = "italic(Archaeoglobus~sulfaticallidus)",     
                    "Desulfovibrio_sp._Dsv1__DsvSp233" = "italic(Desulfovibrio)~species~APFI01000049",
                    "Desulfotomaculum_hydrothermale__DscHydr2" = "italic(Desulfotomaculum~hydrothermale)",
                    "Desulfovibrio_africanus__DslAfri3" = "italic(Desulfovibrio~africanus)",
                    "uncultured_bacterium__EF645665" = "uncultured~italic(Desulfovibrio)~species~EF645665",
                    "Desulfovibrio_carbinoliphilus__JQ031012" = "italic(Desulfovibrio~carbinoliphilus)",
                    "Desulfovibrio_desulfuricans__DslDes16_DsvAlas8" = "italic(Desulfovibrio~desulfuricans)~NC_007519",
                    "Desulfovibrio_desulfuricans__DQ092635" = "italic(Desulfovibrio~desulfuricans)~DQ092635",
                    "uncultured_bacterium__EF645664" = "uncultured~italic(Desulfovibrio)~species~EF645664",
                    "Rice_field_soil_clone_Bu-23__JN615148" = "'uncultured bacterium from rice field'",
                    "Anaerobic_bacterium_EtOH8__Bv2EtOH2" = "'uncultured Firmicute from industrial environment AY751284'",
                    "Desulfovibrio_simplex__DslSimpl" = "italic(Desulfovibrio~simplex)",
                    "Polluted_aquifer_clone_LGWK16__UncS1633" = "'uncultured Firmicute from aquifer'",
                    "Bioreactor_clone__UncS2029" = "'uncultured Firmicute from bioreactor'",
                    "Desulfurispora_thermophila__DprTher2" = "italic(Desulfurispora~thermophila)")


firmicute_orange <- brewer.pal(2, "Set2")[2]
desulfovibrionaceae_purple <- brewer.pal(10, "Set3")[10]
```

```{r}
firmicutes_node <- MRCA(rooted_ref_tree, "Gordonibacter_pamelaeae__GrdPame5", "Polluted_aquifer_clone_LGWK16__UncS1633")
firmicutes_subset_tree <- tree_subset(rooted_ref_tree, firmicutes_node, levels_back = 0)

firmicutes_subset_tree_plot <- ggtree(firmicutes_subset_tree)

inset_firmicutes <- firmicutes_subset_tree_plot +
  geom_tippoint(aes(subset = label %in% hit_otus), size = 1.5, color = firmicute_orange) +
  geom_text_repel(aes(subset = label %in% hit_otus,
                    label = species_labels[label]), 
                  parse = TRUE,
                  size = 3.5, 
                  align = F, 
                  hjust = 0,
                  nudge_x = 1,
                  direction = "y", 
                  force = 0.5, 
                  force_pull = 0.1,
                  max.overlaps = Inf,
                  min.segment.length = 0,
                  box.padding = 0.1,
                  segment.size = 0.25,
                  segment.linetype = "dashed") +
  theme(legend.position = "right",
        plot.margin = margin(5, 10, 5, 5)) +  # Right margin for labels
  hexpand(0.2, direction = 1)
  
inset_firmicutes

ggsave(paste0(figureDir, "NCBI_tree_firmicutes.png"),
       width = 10, height = 10, units = "in",   # increase for larger output
       dpi = 600)

desulfovibionaceae_node <- MRCA(rooted_ref_tree, "uncultured_bacterium__EF645666", "Desulfovibrio_desulfuricans__DslDes24")
desulfovibrionaceae_subset_tree <- tree_subset(rooted_ref_tree, desulfovibionaceae_node, levels_back = 0)

desulfo_subset_tree_plot <- ggtree(desulfovibrionaceae_subset_tree) 

inset_desulfo <- desulfo_subset_tree_plot +
  geom_tippoint(aes(subset = label %in% hit_otus), size = 1.5, color = desulfovibrionaceae_purple) +
  geom_text_repel(aes(subset = label %in% hit_otus,
                    label = species_labels[label]), 
                  parse = TRUE,
                  size = 3.5, 
                  align = F, 
                  hjust = 0, 
                  nudge_x = 0.2,
                  direction = "y", 
                  force = 0.5,
                  force_pull = 0.1,
                  max.overlaps = Inf,
                  min.segment.length = 0,
                  box.padding = 0.1,
                  segment.size = 0.25,
                  segment.linetype = "dashed") +
  theme(legend.position = "right",
        plot.margin = margin(5, 10, 5, 5)) +
  hexpand(0.2, direction = 1)
 
inset_desulfo

ggsave(paste0(figureDir, "NCBI_tree_desulfovibrio.png"),
       width = 10, height = 10, units = "in",
       dpi = 600)
```
