---
title: "asrABC Capscan Analysis"
date: "23 December 2025"
author: "Elizabeth Daigle"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Read in packages and functions
```{r}
source(paste0(here::here(), "/1-Config/config.R"))
```

# read in unique dsr clusters
```{r}
dsr_unique <- readRDS(paste0(dataDir, "/samples_unique_genes_with_names_2015.rds"))
```

```{r}
asr_unique <- readRDS(paste0(dataDir, "/asr_unique_cluster.rds"))
```

# Making color palettes for plots
```{r}
# Generate a viridis palette with 20 colors
viridis_palette <- viridis(20)
viridis_palette

boxplot_colors <- c(viridis_palette[6], viridis_palette[16])
gene_colors <- c("#D98E21", "#6B8E23")
sample_type_colors <- c("#AA3377", "#6F7042")

jitter_colors <- c("#4477AA", "#59A075", "#AA3377", "#DDAA33", "#6F7042")
```

# get summary statistics for Figure 6A
```{r}
unique_hits_summary_dsr <- dsr_unique %>%
  filter(single_closest_ref != "Moorella_thermoacetica_Y72_copy_2__MooTher5") %>%
  # find unique contigs in each coassembly
  # don't care about how we are selecting a subunit here since we just want overall count. RPKG will be in figure part b
  group_by(subject, contig, sample_type) %>%
  slice_max(RPKG, n = 1, with_ties = FALSE) %>%
  ungroup %>%
  # find how many contigs are in each capsule type and stool
  group_by(subject, sample_type) %>%
  summarize(number_hits=n()) %>%
  group_by(sample_type) %>%
  # add up all the hits found in each subject for a given Type. take the median and find IQR
  summarize(n_hits_total=sum(number_hits), median_hits=median(number_hits), q_25=quantile(number_hits, probs=0.25), q_75=quantile(number_hits, probs=0.75)) %>%
  mutate(hits_per_subj = paste0(median_hits, " [IQR ", q_25, "-", q_75, "]")) %>%
  select(sample_type, n_hits_total, hits_per_subj)

unique_hits_summary_asr <- asr_unique %>%
  group_by(subject, contig, sample_type) %>%
  slice_max(RPKG, n = 1, with_ties = FALSE) %>%
  ungroup %>%
  group_by(subject, sample_type) %>%
  summarize(number_hits=n()) %>%
  group_by(sample_type) %>%
  summarize(n_hits_total=sum(number_hits), median_hits=median(number_hits), q_25=quantile(number_hits, probs=0.25), q_75=quantile(number_hits, probs=0.75)) %>%
  mutate(hits_per_subj = paste0(median_hits, " [IQR ", q_25, "-", q_75, "]")) %>%
  select(sample_type, n_hits_total, hits_per_subj)

## for these, the dsr hits get filtered by dups, etc. 
figure_6a <- unique_hits_summary_dsr %>% left_join(., unique_hits_summary_asr, by = "sample_type", suffix = c("_dsr", "_asr"))
```

# How do RPKGs compare to the dsrAB genes? 
# Cannot plot total RPKG since asrABC protein has 3 subunits while dsrAB has 2.
# Using median to account for this
```{r}
# Get median RPKG across contigs in each sample
# then find the sum of RPKG per 1000 cells in a sample
plot_RPKG_dsr_median <- dsr_unique %>%
  filter(single_closest_ref != "Moorella_thermoacetica_Y72_copy_2__MooTher5") %>%
  group_by(sample, contig, sample_type, subject) %>%
  summarize(n=n(), median_RPKG=median(RPKG)*1000) %>%
  ungroup() %>%
  group_by(sample, subject, sample_type) %>%
  summarize(sum_RPKG_per_1000=sum(median_RPKG)) 

plot_RPKG_asr_median <- asr_unique %>%
  group_by(sample, contig, sample_type, subject) %>%
  summarize(n=n(), median_RPKG=median(RPKG)*1000) %>%
  ungroup() %>%
  group_by(sample, subject, sample_type) %>%
  summarize(sum_RPKG_per_1000=sum(median_RPKG))


##this is what i was doing previously 
#plot_RPKG_asr_median <- asr_unique %>%
 # group_by(subject, sample, Type, contig) %>%
  #summarize(n=n(), median_RPKG=median(RPKG), q_25=quantile(RPKG, probs=0.25), q_75=quantile(RPKG, probs=0.75)) %>%
  #group_by(sample) %>%
  #summarize(sum=sum(median_RPKG)) %>%
  #left_join(asr_unique %>%
   #           select(sample, subject, Type, sample_type) %>%
    #          distinct(), by = "sample")
  
```


#box and jitter of both gene clusters
```{r}
# combine asr and dsr data
all_genes <- bind_rows(
  dsr = plot_RPKG_dsr_median,
  asr = plot_RPKG_asr_median,
  .id = "gene_cluster")

# plot a box for each cluster for each type, facet by subject
all_genes %>%
  #filter(subject==9) %>%
  ggplot(aes(x = sample_type, y = log10(sum_RPKG_per_1000), fill = gene_cluster)) +
  geom_boxplot(color = "black",
               position = position_dodge(width = 0.8),
               width = 0.6,
               outlier.shape = NA) +
  # Jitter points with viridis colors
  geom_jitter(aes(color = gene_cluster),
              alpha = 0.8, 
              size = 1.6,
              position = position_jitterdodge(jitter.width = 0.15, jitter.height = 3, dodge.width = 0.8)) +
  scale_color_manual(values = gene_colors, labels = list(expression(italic(asrABC)), expression(italic(dsrAB)), parse = TRUE)) +
  scale_fill_manual(values = c("transparent", "transparent"), guide = "none") +
  guides(fill = "none") +
  facet_wrap(~ subject, 
             #scales = "free_y",
             strip.position = "top",
             labeller = labeller(subject = function(x) paste("Subject", x))) +
  labs(
    title = expression(paste("Abundance of ", italic(asrABC), " vs. ", italic(dsrAB), " by sample type across subjects")),
    subtitle = "Each point represents a sample",
    x = "Sample type",
    #median was taken across a contig to account for subunits
    y = "log10(sum of RPKG)",
    color = "Gene cluster"
  ) +
  theme_bw() +
  guides(
    color = guide_legend(
      override.aes = list(size = 5)
    )) +
  theme(
    axis.text.x = element_text(size = 14, angle = 60, hjust = 1),
    axis.text.y = element_text(size = 14),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.position = "right",
    legend.text  = element_text(size = 12),
    legend.title = element_text(size = 14),
    strip.placement = "outside",
    strip.background = element_blank(),
    strip.text.x = element_text(size = 12),
    plot.title = element_text(size = 20, hjust = 0.5),
    plot.subtitle = element_text(size = 14, hjust = 0.5))


ggsave("median_RPKG_asrABC_v_dsrAB.png",
       width = 11, height = 8, units = "in",   # increase for larger output
       dpi = 600)
```
```{r}
all_genes_subset <- all_genes %>%
  group_by(sample) %>%
  filter(all(c("dsr", "asr") %in% gene_cluster)) %>%
  ungroup()

plot_ratios <- all_genes_subset %>%
  pivot_wider(names_from = gene_cluster, values_from = sum_RPKG_per_1000) %>%
  mutate(ratio_dsr_asr = dsr/asr) 

plot_ratios %>%
  ggplot(aes(x = sample_type, y = log2(ratio_dsr_asr))) +
  geom_boxplot(color = "black",
               position = position_dodge(width = 0.8),
               width = 0.6,
               outlier.shape = NA) +
  geom_jitter(aes(color = sample_type),
              alpha = 0.8, 
              size = 3,
              position = position_jitterdodge(jitter.width = 0.15, jitter.height = 3, dodge.width = 0.8)) +
  scale_color_manual(values = sample_type_colors) +
  guides(
    color = guide_legend(
      override.aes = list(size = 5)
    )) +
  labs(
    title = expression(paste("Comparing ", italic(dsrAB), " to ", italic(asrABC), " abundances in the small and large intestines")),
    x = "Sample type",
    y = expression(paste("Ratio of ", italic(dsrAB), " to ", italic(asrABC))),
    color = "Sample type"
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(size = 14, angle = 60, hjust = 1),
    axis.text.y = element_text(size = 14),
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16),
    legend.position = "right",
    legend.text  = element_text(size = 14),
    legend.title = element_text(size = 14),
    plot.title = element_text(size = 20, hjust = 0.5))

ggsave("ratio_RPKG_asrABC_v_dsrAB.png",
       width = 11, height = 8, units = "in",   # increase for larger output
       dpi = 600)
  
```

