---
title: "SSRMprevalence"
output: html_document
author: "Elizabeth Daigle"
date: "16 April 2026"
---
# this .rmd gets the sample prevalence of SSRMs by age 
# also calculates number of countries represented 

# Read in packages and functions
```{r}
source(paste0(here::here(), "/1-Config/config.R"))
```
# Read in metadata and hits from dm_NCBI.Rmd
```{r}
metadata_final <- readRDS(paste0(dataDir, "/metadata_final.rds"))

# remove hits that were not inserted properly or are too far (Moorella thermoacetica)
hits_final_ages <- readRDS(paste0(dataDir, "/hits_final_sample_prev.rds")) %>%
  filter(!SRM_present == FALSE) %>%
  filter(!single_closest_ref == "Moorella_thermoacetica_Y72_copy_2__MooTher5")
```


# calculate SSRM sample prevalence
# grouping by biosample avoids the need to remove the excess query IDs (some samples have multiple)
```{r}
n_samples <- n_distinct(metadata_final$sample_id)

n_samples_under_3 <- n_distinct(metadata_final$sample_id[metadata_final$under_over_3 == "under 3"])

n_samples_over_3 <- n_distinct(metadata_final$sample_id[metadata_final$under_over_3 == "over 3"])

overall <- hits_final_ages %>%
  summarize(n_biosamples_hits = n_distinct(biosample_id)) %>%
  mutate(n_biosamples_total = n_samples) %>%
  mutate(sample_SSRM_prevalence = round(n_biosamples_hits/n_biosamples_total, digits = 4)) %>%
  mutate(percentage = round(sample_SSRM_prevalence*100, digits = 2)) %>%
  mutate(group = "All ages")

under_3 <- hits_final_ages %>%
  filter(under_over_3 == "under 3") %>%
  summarize(n_biosamples_hits = n_distinct(biosample_id)) %>%
  mutate(n_biosamples_total = n_samples_under_3) %>%
  mutate(sample_SSRM_prevalence = round(n_biosamples_hits/n_biosamples_total, digits = 4)) %>%
  mutate(percentage = round(sample_SSRM_prevalence*100, digits = 2)) %>%
  mutate(group = "Subjects under age 3")

over_3 <- hits_final_ages %>%
  filter(under_over_3 == "over 3") %>%
  summarize(n_biosamples_hits = n_distinct(biosample_id)) %>%
  mutate(n_biosamples_total = n_samples_over_3) %>%
  mutate(sample_SSRM_prevalence = round(n_biosamples_hits/n_biosamples_total, digits = 4)) %>%
  mutate(percentage = round(sample_SSRM_prevalence*100, digits = 2)) %>%
  mutate(group = "Subjects over age 3")

prevalence <- bind_rows(overall, under_3, over_3) %>%
  relocate(group, .before = n_biosamples_hits)
```

# number of countries 
```{r}
countries <- metadata_final %>% 
  mutate(country = case_when(
    str_detect(country, "USA") ~ "United States of America",
    TRUE ~ country)) %>%
  group_by(country) %>% 
  summarize(n=n())
```

